### ISSUE TITLE
F-Droid Repo

### ISSUE THREAD

**Issue by pedrogpimenta** [btmura/rbb#300]
The app isn't updated in the F-Droid repository. Could you provide me with .apk build so I can upload it? :) Thanks!

**Comment by btmura** [comment]
This is the first time I've created an APK for the FOSS version for the F-Droid repository. So, it's likely to be signed differently from the prior versions. You'll need to remove the prior version to install this one. 

You can grab it here: https://sites.google.com/site/btmura/code/rbb/rbb-3.4-foss.apk?attredirects=0&d=1
